### ISSUE TITLE
Add additional setup instructions + project context

### ISSUE THREAD

**Issue by Cooper-Kunz** [hashgraph/hedera-hcs-erc721-sample#1]
Currently, the README showcases a few of the "State APIs" that are available:

- Get information
- Get token
- Get account
- Get transactions

The readme should be updated to (at minimum) include: 

- What the project is (an ERC-721 implementation using HCS) & what's included
- What is a nonfungible token & why ERC-721 is a standard worth using
- Setup/installation instructions for the most popular deployment(s)
- Basic examples of how to create an ERC-721 token and view its contents 

Additionally, there seem to be examples/demos in TypeScript and Swift. The TypeScript section of `/examples` doesn't have any setup instructions nor README itself (is this just the UI?) and the Swift section of `/examples` includes instructions for creating what is presumably a genesis key (?) but I'm not actually sure what is happening. If these examples work together, they should be explained in greater detail and included in the README, but regardless they need more context (e.g. what is the key I'm generating, how is it used in relation to the tokens, etc.)

**Comment by mehcode** [comment]
Thanks @Sheng-Long for writing that up. ❤️
